Fix chrono::Utc for windows (add missing features)
Now it fails [1]:

    error[E0599]: no function or associated item named `now` found for struct `Utc` in the current scope
       --> src\view\processes_view.rs:341:37
        |
    341 |             .unwrap_or_else(|| Utc::now().with_timezone(&UTC));
        |                                     ^^^ function or associated item not found in `Utc`

  [1]: https://github.com/azat/chdig/actions/runs/7333205128/job/19968365371

P.S. I guess now I have to do everything via pull requests...