Show flamegraph render errors (likely due to SIGWINCH)
In case of SIGWINCH the tfg exists with the following stacktrace:

    Traceback (most recent call last):
      File "/src/python/tfg/tfg/browser/terminal.py", line 93, in _draw_frame
        self._win.addstr(y, vf.x, vf.text, attrs)
    _curses.error: addwstr() returned ERR

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/src/python/tfg/./tfg.py", line 7, in <module>
        main()
      File "/src/python/tfg/tfg/main.py", line 70, in main
        process_args(parser.parse_args())
      File "/src/python/tfg/tfg/main.py", line 39, in process_args
        browser.display()
      File "/src/python/tfg/tfg/browser/terminal.py", line 274, in display
        curses.wrapper(self._display)
      File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
        return func(stdscr, *args, **kwds)
      File "/src/python/tfg/tfg/browser/terminal.py", line 290, in _display
        win.draw()
      File "/src/python/tfg/tfg/browser/terminal.py", line 75, in draw
        self._draw_frame(vf, y)
      File "/src/python/tfg/tfg/browser/terminal.py", line 95, in _draw_frame
        raise BrowserException('error: {}, x: {}, y: {}, text: {}'.format(
    tfg.browser.terminal.BrowserException: error: addwstr() returned ERR, x: 146, y: 78, text: D

And this happens in case of screen size became smaller, bigger is ok,
but it will re-draw correctly, so add few comments into the code what
should be done to overcome this limitation.

It had not been done right now since it requires two more dependencies
(nix and signal_hook), and also some code, while the major goal is to
rewrite tfg to rust.