Run cargo update to fix dependencies after version bump
    $ cargo build
    error: failed to select a version for `clap`.
        ... required by package `chdig v0.4.0 (/src/ch/tools/chdig)`
    versions that meet the requirements `*` (locked to 2.34.0) are: 2.34.0

    the package `chdig` depends on `clap`, with features: `derive` but `clap` does not have these features.

    failed to select a version for `clap` which could resolve this conflict