fix `cargo build`
When I tried to build from source, it failed with following error.

Updating git repository https://github.com/azat-rust/cursive
error: failed to load source for dependency cursive
Caused by:
  Unable to update https://github.com/azat-rust/cursive?branch=chdig-25.7#2c18a81a
Caused by:
  failed to fetch into: /home/kavi/.cargo/git/db/cursive-6ea9b78501fad33c
Caused by:
  revision 2c18a81add64a3c4fa844ade56688905ac7361c7 not found
Caused by:
  failed to authenticate when downloading repository: git@github.com:azat-rust/cursive
  * attempted ssh-agent authentication, but no usernames succeeded: git
  if the git CLI succeeds then net.git-fetch-with-cli may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
Caused by:
  no authentication methods succeeded

Adding `net.git-fetch-with-cli` to $HOME/.cargo/config.toml fixed the
issue.

Reference: https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Signed-off-by: Kaviraj <kavirajkanagaraj@gmail.com>