Fix possible panic due to overflow on substraction
One real:

    thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/view/summary_view.rs:381

And other is theoritcal